export const SET_RESERVATION_SEATS = "SET_RESERVATION_SEATS";
export const SET_RESERVATION_DATE = "SET_RESERVATION_DATE";
export const SET_RESERVATION_HOUR = "SET_RESERVATION_HOUR";
export const SET_RESTAURANT = "SET_RESTAURANT";
export const ADD_FOOD = "ADD_FOOD";
export const REMOVE_FOOD = "REMOVE_FOOD";
export const CLEAR_FOODS = "CLEAR_FOODS";
