export const WINDOW_RESIZED = "WINDOW_RESIZED";
export const OPEN_ORDER_MODAL = "OPEN_ORDER_MODAL";
export const OPEN_RESET_PASSWORD = "OPEN_RESET_PASSWORD";
export const OPEN_CHANGE_NUMBER = "OPEN_CHANGE_NUMBER";
