export const ON_RESTAURANTS_FETCH = "ON_RESTAURANTS_FETCH";
export const ON_RESTAURANTS_FETCH_SUCCESS = "ON_RESTAURANTS_FETCH_SUCCESS";
export const ON_RESTAURANTS_FETCH_FAIL = "ON_RESTAURANTS_FETCH_FAIL";
