export const foodsData = [
  {
    type: "Mėsos patiekalai",
    title: "Chick mania",
    description:
      "Sultinga ant grotelių kepta vištiena, čederio sūris, Iceberg salatos, pomidoras, karamelizuotas svogūnas, specialus MAD padažas ir teriyaki padažas, supakuotas į brioche bandelę",
    price: 7.15,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Kesadilija",
    title: "Veg quesadilla",
    description:
      "Quesadilla with Mozzarella cheese, Crispy onion, green and red capsicum, sweet corn, cherry tomato, black olive and green olive",
    price: 6.45,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Picos su mėsa",
    title: "Vezuvijaus 30 cm",
    description: "Kumpis, mocarela, pomidorų padažas",
    price: 9.25,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Žuvies patiekalai",
    title: "Ant griliaus kepta tuno filė su imbieriniu padažu",
    description: "Patiekiama su keptais pomidorais ir bulvių kroketais",
    price: 15.75,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Picos su mėsa",
    title: "Polina 30 cm",
    description:
      "Vištienos krūtinėlė, mocarela, pievagrybiai, paprikos, pomidorų padažas, kario padažas",
    price: 9.5,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Picos su mėsa",
    title: "Capricciosa 30 cm",
    description: "Kumpis, mocarela, pievagrybiai, pomidorų padažas.",
    price: 9.5,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Picos su mėsa",
    title: "Azteca. Aštri 30 cm",
    description:
      "Kumpis, mocarela, salsa, grietinė su uoginėmis paprikomis, pomidorų padažas",
    price: 9.9,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Picos su mėsa",
    title: "Sazia 30 cm",
    description:
      "Vištienos krūtinėlė, kepta kiauliena, bekoniena, mocarela, pomidorai, pomidorų padažas, svogūnai, kepsnių padažas.",
    price: 12,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Picos su mėsa",
    title: "Rossa. Aštri 30 cm",
    description:
      "Kepta kiauliena, bekoniena, mocarela, pomidorai, kepti česnakai, pomidorų padažas, salsa, uoginės paprikos, aitriosios paprikos.",
    price: 11,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Picos su mėsa",
    title: "Cappero 30 cm",
    description:
      "Vytintas serrano kumpis, vyšninė mocarela, mocarela, pomidorai, parmezanas, pomidorų padažas, pesto padažas, kaparėliai, rukola.",
    price: 10.9,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Picos su žuvimi",
    title: "Marinara 30 cm",
    description:
      "Krevetės, lašišų file, mocarela, rikotos kremas su špinatais, pomidorų padažas.",
    price: 13.99,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Vegetariškos picos",
    title: "Margarita 30 cm",
    description: "Mocarela, pomidorų padažas.",
    price: 7.5,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Vegetariškos picos",
    title: "Ricotta formaggio 30 cm",
    description:
      "Mocarela, varškės sūris, ožkos sūris, parmezanas, pomidorai, pomidorų padažas, rikotos kremas su špinatais",
    price: 11.5,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Desertai",
    title: "Naminis obuolių pyragas",
    description: "Su vaniliniais ledais",
    price: 5.9,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Desertai",
    title: "Varškės štrudelis",
    description: "Su vanilės užpilu",
    price: 6.5,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Desertai",
    title: "Šokoladinis suflė",
    description:
      "Chocolate lava cake su vyšnių padažu, ledais ir karštu baltu šokoladu",
    price: 6,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Desertai",
    title: "Kepti varškėčiai su grietinės ir vyšnių padažu",
    description: "Skanūs varškėčiai su ypatingu padažu",
    price: 7.9,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Desertai",
    title: "Virti varškėtukai su grietine ir aviečių padažu",
    description: "Nuostabus aviečių padažas",
    price: 7.8,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Gėrimai",
    title: "Coca cola",
    description: null,
    price: 2.7,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Gėrimai",
    title: "Fanta",
    description: null,
    price: 2.7,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Gėrimai",
    title: "Sprite",
    description: null,
    price: 2.7,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Gėrimai",
    title: "Acqua panna",
    description: null,
    price: 2.65,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Gėrimai",
    title: "Šviežiai spaustos sultys 0,2 l",
    description: null,
    price: 3.7,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Gėrimai",
    title: "Šviežiai spaustos sultys 0,5 l",
    description: null,
    price: 7.5,
    restaurant: "ngIifs0kJy7VXs7iD9HW",
  },
  {
    type: "Kesadilija",
    title: "Jautienos kesadilija",
    description:
      "Meksikietiškas patiekalas, gaminamas užpilant tortiliją sūriu, meksikietiškai virta jautiena, kapotomis raudonosiomis ir žaliosiomis paprikomis ir džiovintais pomidorais, perlenkiant per pusę ir skrudinant, kol sūris išsilydys.",
    price: 8.2,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Kesadilija",
    title: "Vištienos kesadilija",
    description:
      "Meksikietiškas patiekalas, gaminamas į tortiliją įdarus sūriu, vištiena, kapotomis raudonosiomis ir žaliosiomis paprikomis, saldžiaisiais kukurūzais, traškiais svogūnais ir džiovintais pomidorais, perlenkiant per pusę ir skrudinant, kol sūris išsilydys.",
    price: 7.99,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Sriuba",
    title: "Jautienos čili con carne sriuba",
    description:
      "Jautienos čili con carne sriuba iš maltos jautienos, česnako, svogūno, morkos, paprikos, žaliųjų žirnelių, grybų ir pomidorų",
    price: 6.5,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Sriuba",
    title: "Manchow vištienos sriuba",
    description:
      "Vištienos Manchow sriuba iš daržovių mišinių, imbiero, česnako, sojos padažo, žaliosios ir raudonosios paprikos",
    price: 6,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Sriuba",
    title: "Vegetariška Manchow sriuba",
    description:
      "Vegetariška Manchow sriuba iš daržovių mišinių, imbiero, česnako, sojos padažo, žaliosios ir raudonosios paprikos",
    price: 5,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Pagrindiniai patiekalai",
    title: "Vištienos kepsnys",
    description: "Vištienos kepsnys su bulvių skiltelėmis ir padažu",
    price: 11.99,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Pagrindiniai patiekalai",
    title: "Lašišos kepsnys",
    description: "Lašišos kepsnys su bulvių skiltelėmis ir padažu",
    price: 14.99,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Užkandžiai",
    title: "Nachos su meksikietiška jautiena",
    description: null,
    price: 8,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Užkandžiai",
    title: "Naminis bulvių sūrio rutuliukas",
    description: null,
    price: 5,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Užkandžiai",
    title: "Mocarelos sūrio rutulys",
    description: null,
    price: 6.5,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Užkandžiai",
    title: "Jalapeno čederio sūrio rutulys",
    description: null,
    price: 6.99,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Užkandžiai",
    title: "Traškūs vištienos sparneliai 6vnt",
    description: null,
    price: 7.99,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Burritos",
    title: "Core burrito",
    description:
      "Meksikietiški ryžiai, kopūstų salotos, iceberg, raudonos pupelės, kukurūzai, bulvytės, papuoštos Aioli padažu",
    price: 6.5,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Burritos",
    title: "Grill Magic",
    description:
      "Meksikietiški ryžiai ant pagrindo su Iceberg, kopūstų salotomis, saldžiaisiais kukurūzais, pupelėmis, kepta teriyaki vištiena, pagardinta specialiu MAD padažu",
    price: 7.75,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Burritos",
    title: "Pork Bite",
    description:
      "Pulled kiauliena, meksikietiški ryžiai, pupelės, iceberg, kopūstų salotos ir padažas",
    price: 7.99,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Burgers",
    title: "Mad Crisp",
    description:
      "Vištienos krūtinėlės virsta traškiu ir auksiniu šnicelių mėsainiu su pomidoru, marinuotu agurku, ledkalnio lapeliu, čederio sūriu, traškiu svogūnu ir specialiu padažu",
    price: 7.5,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Burgers",
    title: "Beef Brat",
    description:
      "Klasikinis mėsainis yra visų laikų BBQ mėgstamiausias! Brioche bandelės, jautienos paplotėlis, traškus svogūnas, čederio sūris, Iceberg salatos, marinuotas agurkas, pomidoras, BBQ padažas",
    price: 7.99,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Burgers",
    title: "„Bloodbath“ aštrus mėsainis su bulvytėmis ir padažu",
    description:
      "Brioche bandelė, rūkytos jautienos smulkus, pomidoras, traškus svogūnas, įdaryti dūminio sūrio, sultenai, šoninė, aštrus Mayo, jalapeno",
    price: 8.49,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Drinks",
    title: "Cola Zero 0,3 l",
    description: null,
    price: 1.8,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Drinks",
    title: "Fanta 0,3 l",
    description: null,
    price: 1.8,
    restaurant: "A5FH9H6brYKbFQnWOx2u",
  },
  {
    type: "Sriubos",
    title: "Burokėlių sriuba",
    description: null,
    price: 2.3,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Sriubos",
    title: "Ant žarijų keptos jautienos ir daržovių sriuba",
    description: null,
    price: 4.6,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Užkandžiai",
    title: "Gruzdintos bulvytės",
    description:
      "Pasirinktinai (skiltelės, laiveliai, šiaudeliai, kroketai) su padažu",
    price: 2.5,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Užkandžiai",
    title: "Kepta duona sūrio padaže",
    description: null,
    price: 3.5,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Užkandžiai",
    title: "Vištienos sparneliai",
    description:
      "Su morkų šiaudeliais ir Tzatziki padažu. Glazūra pasirinktinai: BBQ, Jameson",
    price: 4.5,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Grill koldūnų iešmelis",
    title: "Grill koldūnų iešmelis su daržovėmis",
    description: null,
    price: 3.9,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Grill koldūnų iešmelis",
    title: "Grill koldūnų iešmelis su vištiena, sūriu ir grybais",
    description: null,
    price: 4.9,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Salotos",
    title: "Keptų daržovių salotos su teriyaki vištienos iešmeliu",
    description: null,
    price: 5.9,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Salotos",
    title: "Cezario salotos su vištienos krūtinėle",
    description: null,
    price: 5.9,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Salotos",
    title: "Cezario salotos su daržovių iešmeliu",
    description: null,
    price: 4.8,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Kepsniai",
    title: "Augalinės Kilmės Beyond Meat maltinukas su Teriyaki",
    description: null,
    price: 8.9,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Kepsniai",
    title: "Vištienos krūtinėlės kepsnys",
    description: null,
    price: 5.5,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Kepsniai",
    title: "Jameson kiaulienos šonkauliai",
    description: null,
    price: 13.6,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Burgeriai",
    title: "BBQ plėšytos kiaulienos burgeris",
    description: null,
    price: 4.8,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Burgeriai",
    title: "Šamo filė burgeris",
    description: null,
    price: 6.8,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Burgeriai",
    title: "Kepto ožkų sūrio burgeris",
    description: null,
    price: 6.8,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Desertai",
    title: "Šokoladinis Brownie pyragas su plakta grietinėle ir vyšniomis",
    description: null,
    price: 3.8,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Desertai",
    title: "Tradicinis angliškas Banoffee pyragas su miško uogų padažu",
    description: null,
    price: 3.8,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Gėrimai",
    title: "Mineralinis vanduo Vichy 0,33 l",
    description: null,
    price: 2,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
  {
    type: "Gėrimai",
    title: "Būkčia Kombučia 0,33 l",
    description: null,
    price: 3.1,
    restaurant: "3Bh14ojrNMtbrbCaR8ne",
  },
];
