export const USER_LOGIN = "user/USER_LOGIN";
export const USER_LOGIN_SUCCESS = "user/USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "user/USER_LOGIN_FAIL";

export const USER_REGISTER = "user/USER_REGISTER";
export const USER_REGISTER_SUCCESS = "user/USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "user/USER_REGISTER_FAIL";
export const USER_LOGIN_WITH_GOOGLE = "user/USER_LOGIN_WITH_GOOGLE";

export const SET_CHANGE_PASSWORD_SUCCESS = "user/SET_CHANGE_PASSWORD_SUCCESS";
export const SET_CHANGE_PASSWORD = "user/SET_CHANGE_PASSWORD";
export const SET_CHANGE_PASSWORD_FAIL = "user/SET_CHANGE_PASSWORD_FAIL";

export const CLEAR_PASSWORD = "user/CLEAR_PASSWORD";

export const SET_CHANGE_PHONE_NUMBER_SUCCESS =
  "user/SET_CHANGE_PHONE_NUMBER_SUCCESS";
export const SET_CHANGE_PHONE_NUMBER = "user/SET_CHANGE_PHONE_NUMBER";
export const SET_CHANGE_PHONE_NUMBER_FAIL = "user/SET_CHANGE_PHONE_NUMBER_FAIL";

export const CLEAR_PHONE_NUMBER = "user/CLEAR_PHONE_NUMBER";

export const SET_NEXT_ROUTE = "SET_NEXT_ROUTE";
export const CLEAR_NEXT_ROUTE = "CLEAR_NEXT_ROUTE";
