export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOGIN_WITH_GOOGLE = "USER_LOGIN_WITH_GOOGLE";

export const SET_CHANGE_PASSWORD_SUCCESS = "SET_CHANGE_PASSWORD_SUCCESS";
export const SET_CHANGE_PASSWORD = "SET_CHANGE_PASSWORD";
export const SET_CHANGE_PASSWORD_FAIL = "SET_CHANGE_PASSWORD_FAIL";
